### PR TITLE
Added roon-extension-rheos

### PR DESCRIPTION
**Pull request by LINVALE**
Jan,

Realize this is difficult to test without Heos Players. Limited "beta testing" but this is working well on my systems and I have tested on various devices. If you accept into the repo I will update as a "pre-release:    v 0.5-00 " and harmonize across docker and GitHub and NPM. I'll then create a new entry in the Community to notify of availability.

Any thoughts and or feedback appreciated. I'll also give some comments on the extension generator and the docker learning. A major help would be to update the standard linux/node image to one that's more to updated. You'll see I settled on the latest alpine based on my testing.

Added in device control: 

        "author": "Linvale",
        "display_name": "Rheos",
        "description": "Connect and Control Denon/Marantz Heos players from Roon",
        "image": {
            "repo": "rheos/roon-extension-rheos",
            "tags": {
                "amd64": "latest",
                "arm": "latest",
                "arm64": "latest"
            },
            "binds": [
                "/home/node/config.json"
            ]
        }

### CODE REVIEW

**Comment by JanKoudijs** [comment]
Hi @LINVALE,

Thanks for submitting the Rheos extension!

I added the entry for the Rheos extension to the v1.x branch of this repo. The master branch belongs to the old version of the Extension Manager (v0.x) and is no longer updated.

The test I perform for an extension for which I do not own the hardware is a basic install and see if the extension appears and (preferably) reports that the device is not found.

The test is successful for amd64, but fails for arm and arm64. It looks like the arm images include non arm executables. I do not know if you have the possibility to test on arm, but if not that's not a real problem as support could be limited to amd64 only.

For the node update, what base image did you switch to? The build system relies on multiarch images for arm image creation. I see that the latest provided is alpine-3.14.

**Comment by LINVALE** [comment]
Thanks Jan.

I will take a look at testing on arms and revising the specific builds for arms. I probably misunderstood the instructions for the build file.

This has been a journey of discovery for me with a great deal of learning! I really appreciate all you have done to try and make this accessible and the work you do.

I'm using node:19-alpine3.15 as this seemed to result in the smallest repo and allow some of the newer js synrtax that caused a problem with the earlier alpine.

**Comment by LINVALE** [comment]
Jan,

I have now updated this and have versions for amd64, arm64 and arm in my repo. I found the script for roon-extension-generator difficult so created my own simple dockerfile and then build the versions using buildx which was (for me at least) easier. I found the alpine image was failing and have moved to 'node:19-bullseye-slim' which is still pretty compact but has all the dependencies it seems needed..

Very impressed with how the extension manager handles this.

I added a (hopefully) graceful exit if the app can not find any HEOS enabled player (Denon/Marantz amps and avrs etc). This exits after 5 minutes of trying. One question - is there a way of indicating this "failure" mode in the extension manager rather than "stopped" perhaps?

I plan on announcing this as a pre-release version in the community (not that I think there are many people other than me needing this!) so wanted o give you a heads up and express my sincere thanks for all the work you have put into this. I really need to improve my understanding of Linux shell commands!

**Comment by JanKoudijs** [comment]
Not sure if something went wrong with the push to Docker Hub, but it has only one image which appears to be for amd64.

**Comment by LINVALE** [comment]
Thanks Jan.

Ill look at it. I must have overwritten the previous builds and am getting an error 

 > [linux/arm/v7 8/8] RUN npm install:
#0 0.215 Error while loading /usr/local/sbin/node: No such file or directory

I am thinking this is my Dockerfile that's no longer copying the local node-modules but cant work out what I have done.  Will continue to work on it ;-)

**Comment by LINVALE** [comment]
Fixed.

Tested on amd64,arm 32 and arm 64.

I don't need to RUN NPM install in my Dockerfile. Still on that learning curve ...

Sorry about that.

Please let me know if you detect other issues.

Peter

**Comment by JanKoudijs** [comment]
I don't have an arm32 setup at the moment but arm64 indeed worked fine.
Time to close this PR

**Pull request closed without merging**
