### PR TITLE
Added Logitech Harmony & Denon AVR repositories

### PR DESCRIPTION
**Pull request by docbobo**
Added the following extensions:

- Logitech Harmony Source Control
- Denon/Marantz AVR Volume Control

I have no idea if this is working, since I don't know how to test this. Feel free to give advice, so that I can validate.

### CODE REVIEW

**Comment by JanKoudijs** [comment]
Hi @docbobo,
Please check [this thread](https://community.roonlabs.com/t/roon-extension-manager-developer-release/26632) on how to install the Extension Manager.

**Comment by docbobo** [comment]
Installing the Extension Manager wasn't the question here. Instead I would like to understand how I can test this PR locally...

**Comment by JanKoudijs** [comment]
The quickest way is to copy your repository.json into the `<extension root>/lib/node_modules/roon-extension-repository/` directory and restart the manager.

**Comment by docbobo** [comment]
Thanks, @JanKoudijs - definitely found a fixed a typo with that. Will try to install the two extension tonight, to see if they are running properly.

**Comment by JanKoudijs** [comment]
Hi @docbobo,
I'm getting host key errors when I try to install the Logitech Harmony extension, also when I try manually using:
`npm install -g https://github.com/docbobo/roon-extension-harmony.git`

**Comment by docbobo** [comment]
Can you quote the exact error message here?

**Comment by JanKoudijs** [comment]
Seems to be related to the swissmanu/harmonyhubjs stuff:

    The authenticity of host 'github.com (192.30.253.113)' can't be established.
    RSA key fingerprint is SHA256:nThbg6...
    RSA key fingerprint is MD5:16:27:ac:a5...
    Are you sure you want to continue connecting (yes/no)?

It asks for input to continue, which my installer doesn't provide.
Anything specific with this library?

    npm ERR! Command failed: git clone --template=/home/Jan/.npm/_git-remotes/_templates --mirror git@github.com:swissmanu/harmonyhubjs-discover.git /home/Jan/.npm/_git-remotes/git-github-com-swissmanu-harmonyhubjs-discover-git-a70c87c0
    npm ERR! Cloning into bare repository '/home/Jan/.npm/_git-remotes/git-github-com-swissmanu-harmonyhubjs-discover-git-a70c87c0'...
    npm ERR! Host key verification failed.
    npm ERR! fatal: Could not read from remote repository.

**Comment by docbobo** [comment]
Interesting. Was able to successfully install and run both extensions. I am running the extension manager inside a clean docker container, so that should work on any clean system...

**Comment by JanKoudijs** [comment]
Looks like an ssh access issue. Did you manually add an ssh key to your known_hosts for github.com?

**Comment by docbobo** [comment]
Nope. As I said: clean docker container. Did you try HTTPS? Why would npm use SSH by default?

**Comment by JanKoudijs** [comment]
I'm passing an https url for installation but during dependency handling it switches to ssh for some reason. I have this problem on my development PC running Fedora and on my NUC running Arch Linux.

Also tried `git clone https://` followed by `npm install` but same result. If I remove the swissmanu/harmonyhubjs dependencies it installs but of course won't work.

**Comment by JanKoudijs** [comment]
If I get the dependencies from the npm repository then it works:

    "harmonyhubjs-client": "^1.1.0",
    "harmonyhubjs-discover": "^1.0.0"

Maybe something to consider.

The dependency list is pretty long but I expect that this is normal.

**Comment by docbobo** [comment]
Weird. Did you check ~/.gitconfig?

**Comment by docbobo** [comment]
And do you get a different result when you do a `npm install https://github.com/docbobo/roon-extension-harmony` instead of `npm install https://github.com/docbobo/roon-extension-harmony.git`?

**Comment by JanKoudijs** [comment]
Nothing ssh in ~/.gitconfig. I only get it installed by making the change I described in my previous comment. Is there a specific reason why you are using a direct github url for the harmonyhubjs dependencies?

**Comment by docbobo** [comment]
What do you mean with direct? Here's the content of the package.json:

```
  "dependencies": {
    "debug": "^2.1.0",
    "harmonyhubjs-client": "github:swissmanu/harmonyhubjs-client",
    "harmonyhubjs-discover": "github:swissmanu/harmonyhubjs-discover",
    "node-roon-api": "github:roonlabs/node-roon-api",
    "node-roon-api-settings": "github:roonlabs/node-roon-api-settings",
    "node-roon-api-source-control": "github:roonlabs/node-roon-api-source-control",
    "node-roon-api-status": "github:roonlabs/node-roon-api-status"
  }
```

What change would you suggest here?

**Comment by JanKoudijs** [comment]
A version specification like you have for debug (accessing the npm repository):

    "dependencies": {
      "debug": "^2.1.0",
      "harmonyhubjs-client": "^1.1.0",
      "harmonyhubjs-discover": "^1.0.0",
      "node-roon-api": "github:roonlabs/node-roon-api",
      "node-roon-api-settings": "github:roonlabs/node-roon-api-settings",
      "node-roon-api-source-control": "github:roonlabs/node-roon-api-source-control",
      "node-roon-api-status": "github:roonlabs/node-roon-api-status"
    }

**Comment by docbobo** [comment]
And why harmonyhub and not roon? (Sorry for asking simple questions here, but those are my first node projects)

**Comment by JanKoudijs** [comment]
A few weeks back I didn't know this either :)

The Roon API is not published on [npm](https://www.npmjs.com/) but harmonyhub is. It showed up in my search, I gave it a try and it worked! The advantage is that you have more control over the version that gets installed (please check if my suggestion is right, only minor version increments).

More info: https://docs.npmjs.com/files/package.json#dependencies

**Comment by docbobo** [comment]
Thanks for the explanation, @JanKoudijs. I've updated the `package.json` for both extensions accordingly. Can you give it another try?

**Comment by JanKoudijs** [comment]
Done, all fine now.
Thanks for joining!

**Pull request merged**
