### PR TITLE
Add Community DJ Extension to the repository

### PR DESCRIPTION
**Pull request by nugget**
Adding the WIP Community DJ extension to the repository.  More information can be found at https://github.com/nugget/roon-community-dj

### CODE REVIEW

**Comment by nugget** [comment]
See also: https://community.roonlabs.com/t/roon-extension-community-dj/103079?u=nugget

**Comment by JanKoudijs** [comment]
Tested installation of the Community DJ extension via the Extension Manager. Two things:

1. After installation two instances of the extension show up. I had a look at your package.json which has a script entry with a start command. Not familiar with this npm feature, so my question is: is this command executed after an `npm install`? That would explain what I see, one instance created by the install and another one by the Extension Manager.

Is it OK for you to remove the script entry, or can you create a branch, to be used by the Extension Manager, without it?

2. The package.json also states that the minimum required node version is 12.x. Do you really use node functionality that requires this version? Currently the Windows installer of the Extension Manager installs 10.15.3.

If you rely on this version then I first have to work on an updated installer, or add new functionality that uses the version information to hide repository entries, before your extension can be included. If it is part of the repository then it should work on the supported platforms.

**Comment by nugget** [comment]
Thanks, I'll validate that the extension works with 10.15.  The 12.x requirement is just a carryover from the other extension I wrote which needs the node-discord library (which does require node 12). This one doesn't, so it will probably be fine in node 10.

The script should only invoked if the user explicitly performs an `npm start`, so I'm not sure why you're seeing two instances launched.  Interestingly, on the server side I am seeing both of your instances firing up with different assigned user ids.  Not quite sure what is going on there.  The script definition isn't integral to the package.json though, just a "best practices" so that it's completely clear which script is the primary for launching since the code is split up across many .js files.

Happy to accommodate however is easiest for you.

```
2020-04-22 17:36:40 MESG {"action":"ANNOUNCE","serverid":"e3df759c-ad17-46a8-b34f-efb25b05d630","channel":"chaos","version":"0.3.3","mode":"slave","enabled":true}
2020-04-22 17:36:40 MESG {"action":"ANNOUNCE","serverid":"1c427125-b55d-4c76-87e4-a8462885b58c","channel":"chaos","version":"0.3.3","mode":"slave","enabled":true}
```

**Comment by nugget** [comment]
Both changes are made to package.json on my end, so you should be good to go now. Thanks!

**Comment by JanKoudijs** [comment]
I have to perform a debug session to find out what is causing this dual startup.

**Comment by JanKoudijs** [comment]
I found the cause of the dual startup of your extension. This bug will be fixed in the upcoming release of the Extension Manager.

**Comment by nugget** [comment]
Excellent news!  I'm glad I could indirectly help.  I assume this means I'd be safe to add my script entry back to `package.json`?

Thanks, again!

**Comment by JanKoudijs** [comment]
Yes, that should be fine.

I've got one for you as well :) Maybe you can have a look at [this](https://github.com/nugget/roon-community-dj/issues/21).

**Pull request merged**
